### ISSUE TITLE
Latest application version isn't pushed to Helm

### ISSUE THREAD

**Issue by evanfoster** [plumber-cd/helm#1]
Hey there! 

I noticed it's been a little bit since a new release was pushed to the Helm repository:

```
❯ helm repo add plumber-cd https://plumber-cd.github.io/helm/

❯ helm search repo plumber-cd --versions
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
plumber-cd/dynamic-pvc-provisioner	0.1.0        	0.2.0      	A Helm chart for Kubernetes
plumber-cd/dynamic-pvc-provisioner	0.0.3        	0.1.1      	A Helm chart for Kubernetes
plumber-cd/dynamic-pvc-provisioner	0.0.2        	0.0.4      	A Helm chart for Kubernetes
plumber-cd/dynamic-pvc-provisioner	0.0.1        	0.0.2      	A Helm chart for Kubernetes
plumber-cd/reclaimable-pv-releaser	0.1.0        	0.2.0      	A Helm chart for Kubernetes
plumber-cd/reclaimable-pv-releaser	0.0.3        	0.1.1      	A Helm chart for Kubernetes
plumber-cd/reclaimable-pv-releaser	0.0.2        	0.0.4      	A Helm chart for Kubernetes
plumber-cd/reclaimable-pv-releaser	0.0.1        	0.0.2      	A Helm chart for Kubernetes
```

Would it be possible to push v0.2.3 of the provisioner and releaser to the Helm repo?

Thanks much!

**Comment by dee-kryvenko** [comment]
Hi @evanfoster, thanks for your interest in the project! I might be misunderstanding Helm, but I do not think this is necessary. There was no changes in the chart in between v0.2.0 and v0.2.3. The `APP VERSION` "bundled" with the chart is just a default value and it is up to the user to set it correctly. Could you point me to some documentation or article so that I can learn please?
